---
boost:
  description: Start a boost
  target:
    entity:
      integration: heatzy
      domain: climate
  fields:
    delay:
      required: true
      name: Delay
      description: Boost delay (minutes)
      selector:
        select:
          translation_key: "boost_delay"
          mode: dropdown
          options:
            - 30
            - 60
            - 90
            - 120

vacation:
  description: Start a vacation
  target:
    entity:
      integration: heatzy
      domain: climate
  fields:
    delay:
      required: true
      name: Delay
      description: Vacation delay (days)
      number:
        unit_of_measurement: "days"
        min: 1
        max: 30
